### ISSUE TITLE
Undefined function error - CAHNRSWP\Plugin\Pagebuilder\cpb_get_post_item()

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/cahnrswp-plugin-pagebuilder#9]
Seeing this in the error logs on the server:

```
[05-Apr-2018 15:24:39 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function CAHNRSWP\Plugin\Pagebuilder\cpb_get_post_item() in /opt/rh/rh-nginx112/root/usr/share/nginx/html/wp-content/plugins/cahnrswsuwp-plugin-pagebuilder/lib/shortcodes/promo/class-promo-shortcode.php:247
Stack trace:
#0 /opt/rh/rh-nginx112/root/usr/share/nginx/html/wp-content/plugins/cahnrswsuwp-plugin-pagebuilder/lib/shortcodes/promo/class-promo-shortcode.php(112): CAHNRSWP\Plugin\Pagebuilder\Promo_Shortcode->get_select_items(Array)
#1 /opt/rh/rh-nginx112/root/usr/share/nginx/html/wordpress/wp-includes/shortcodes.php(319): CAHNRSWP\Plugin\Pagebuilder\Promo_Shortcode->get_rendered_shortcode(Array, '', 'promo')
#2 [internal function]: do_shortcode_tag(Array)
#3 /opt/rh/rh-nginx112/root/usr/share/nginx/html/wordpress/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(promo)...', 'do_shortcode_ta...', '[promo post_ids...')
#4 /opt/rh/rh-nginx112/root/usr/share/nginx/html/wp-content/plugins/cahnrswsuwp-plugin-pagebuilder/lib/shortcodes/column/column.min.php(3): in /opt/rh/rh-nginx112/root/usr/share/nginx/html/wp-content/plugins/cahnrswsuwp-plugin-pagebuilder/lib/shortcodes/promo/class-promo-shortcode.php on line 247
```

**Comment by danialbleile** [comment]
Just saw this on our server as well. I've posted the error here: https://github.com/washingtonstateuniversity/CAHNRSWSUWP-Plugin-Pagebuilder/issues/11
